language: go
go:
  - "1.13.x"
  - tip

env:
  global: GOFLAGS=-mod=vendor

install:
- make deps

script:
- make lint
- make vet
- make test
- make website-test
- make website-lint

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
